create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  category text not null check (char_length(category) between 1 and 80),
  summary text not null check (char_length(summary) between 1 and 600),
  canva_url text,
  thumbnail_url text,
  sort_order smallint not null unique check (sort_order between 1 and 99),
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254),
  message text not null check (char_length(message) between 10 and 3000),
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.contact_messages enable row level security;

grant select on table public.projects to anon, authenticated;
grant insert on table public.contact_messages to anon, authenticated;
grant usage, select on sequence public.contact_messages_id_seq to anon, authenticated;

create policy "Published projects are publicly readable"
on public.projects
for select
to anon, authenticated
using (is_published = true);

create policy "Visitors can submit contact messages"
on public.contact_messages
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 100
  and char_length(email) between 3 and 254
  and char_length(message) between 10 and 3000
);

insert into public.projects (title, category, summary, sort_order, is_published)
values
  ('Project One', 'Brand & visual story', 'A featured case study ready for Lauren''s first project, process notes, and final presentation.', 1, true),
  ('Project Two', 'Research & strategy', 'A flexible space for the problem, Lauren''s approach, and the decisions behind the finished work.', 2, true),
  ('Project Three', 'Digital experience', 'A polished project preview designed to link to or embed a shared Canva presentation.', 3, true),
  ('Project Four', 'Creative exploration', 'A final showcase slot for an experiment, passion project, or collaborative piece.', 4, true);
